import type { ActivityItem, Company, SearchHistoryItem } from "./types";

/**
 * Local dataset used only to render the interface while the Spring Boot REST
 * API is being wired. No business rule lives here — it is display data.
 */

const photo = (seed: string) =>
  `https://images.unsplash.com/photo-${seed}?auto=format&fit=crop&w=1200&q=70`;

const officePhotos = [
  photo("1497366216548-37526070297c"),
  photo("1524758631624-e2822e304c36"),
  photo("1497366754035-f200968a6e72"),
];

export const companies: Company[] = [
  {
    id: "1",
    name: "Moretti & Advogados Associados",
    category: "Escritório de Advocacia",
    address: "Rua Boa Morte, 1420 - Centro",
    city: "Limeira",
    state: "SP",
    phone: "+55 19 3441-8820",
    website: "https://morettiadvogados.com.br",
    rating: 4.8,
    reviews: 214,
    openingHours: "Seg a Sex · 08:00 - 18:00",
    tags: ["Empresarial", "Tributário", "Alto ticket"],
    aiScore: 92,
    aiSummary:
      "Escritório consolidado com forte presença digital e demanda clara por automação de atendimento. Alta aderência ao produto.",
    favorite: true,
    stage: "reuniao-agendada",
    createdAt: "2026-07-24T10:12:00Z",
    photos: officePhotos,
    notes: "Sócio-diretor respondeu no WhatsApp e pediu proposta para julho.",
  },
  {
    id: "2",
    name: "Vertex Contabilidade Digital",
    category: "Escritório de Contabilidade",
    address: "Av. Antônio Ometto, 980 - Jardim Nova Europa",
    city: "Limeira",
    state: "SP",
    phone: "+55 19 3702-1155",
    website: "https://vertexcontabil.com.br",
    rating: 4.6,
    reviews: 138,
    openingHours: "Seg a Sex · 09:00 - 18:00",
    tags: ["Contábil", "SaaS friendly"],
    aiScore: 87,
    aiSummary: "Já utiliza ferramentas digitais; ciclo de compra curto e decisor acessível.",
    favorite: false,
    stage: "primeiro-contato",
    createdAt: "2026-07-24T09:40:00Z",
    photos: officePhotos,
  },
  {
    id: "3",
    name: "Clínica OdontoPrime",
    category: "Clínica Odontológica",
    address: "Rua Santa Cruz, 210 - Vila Cidade Jardim",
    city: "Piracicaba",
    state: "SP",
    phone: "+55 19 3433-7788",
    website: "https://odontoprime.com.br",
    rating: 4.9,
    reviews: 512,
    openingHours: "Seg a Sáb · 08:00 - 20:00",
    tags: ["Saúde", "Alto volume"],
    aiScore: 74,
    aiSummary: "Volume alto de pacientes, porém decisão pulverizada entre sócios.",
    favorite: false,
    stage: "novo-lead",
    createdAt: "2026-07-23T16:05:00Z",
    photos: officePhotos,
  },
  {
    id: "4",
    name: "Grupo Ferreira Imobiliária",
    category: "Imobiliária",
    address: "Av. Independência, 3300 - Alemães",
    city: "Piracicaba",
    state: "SP",
    phone: "+55 19 3421-4400",
    website: "https://grupoferreira.com.br",
    rating: 4.3,
    reviews: 96,
    openingHours: "Seg a Sex · 08:30 - 18:30",
    tags: ["Imobiliário", "Franquia"],
    aiScore: 81,
    favorite: true,
    stage: "proposta-enviada",
    createdAt: "2026-07-23T11:22:00Z",
    photos: officePhotos,
  },
  {
    id: "5",
    name: "NorthPeak Software House",
    category: "Desenvolvimento de Software",
    address: "Rua Riachuelo, 45 - Centro",
    city: "Campinas",
    state: "SP",
    phone: "+55 19 3255-9010",
    website: "https://northpeak.dev",
    rating: 5,
    reviews: 64,
    openingHours: "Seg a Sex · 09:00 - 19:00",
    tags: ["Tech", "Parceria"],
    aiScore: 95,
    aiSummary: "Perfil ideal de parceiro white-label. Pronto para negociação imediata.",
    favorite: true,
    stage: "negociacao",
    createdAt: "2026-07-22T14:10:00Z",
    photos: officePhotos,
  },
  {
    id: "6",
    name: "Belluno Restaurante",
    category: "Restaurante",
    address: "Rua Barão de Campinas, 77 - Centro",
    city: "Campinas",
    state: "SP",
    phone: "+55 19 3234-1120",
    website: "https://belluno.com.br",
    rating: 4.4,
    reviews: 1280,
    openingHours: "Ter a Dom · 11:30 - 23:00",
    tags: ["Food service"],
    aiScore: 48,
    aiSummary: "Baixa aderência: ticket reduzido e ausência de time comercial.",
    favorite: false,
    stage: "perdido",
    createdAt: "2026-07-21T19:30:00Z",
    photos: officePhotos,
  },
  {
    id: "7",
    name: "Atlas Logística Integrada",
    category: "Transportadora",
    address: "Rod. Anhanguera, km 118 - Distrito Industrial",
    city: "Americana",
    state: "SP",
    phone: "+55 19 3604-2200",
    website: "https://atlaslog.com.br",
    rating: 4.1,
    reviews: 73,
    openingHours: "24 horas",
    tags: ["Logística", "Enterprise"],
    aiScore: null,
    favorite: false,
    stage: "novo-lead",
    createdAt: "2026-07-21T08:45:00Z",
    photos: officePhotos,
  },
  {
    id: "8",
    name: "Studio Lumen Arquitetura",
    category: "Escritório de Arquitetura",
    address: "Rua dos Ipês, 302 - Jardim Paulista",
    city: "Americana",
    state: "SP",
    phone: "+55 19 3461-7788",
    website: "https://studiolumen.arq.br",
    rating: 4.7,
    reviews: 41,
    openingHours: "Seg a Sex · 09:00 - 18:00",
    tags: ["Criativo", "Ticket médio"],
    aiScore: null,
    favorite: false,
    stage: "novo-lead",
    createdAt: "2026-07-20T15:00:00Z",
    photos: officePhotos,
  },
  {
    id: "9",
    name: "Nexo Marketing Performance",
    category: "Agência de Marketing",
    address: "Av. Brasil, 1200 - Jardim Guanabara",
    city: "Campinas",
    state: "SP",
    phone: "+55 19 3288-4545",
    website: "https://nexoperformance.com.br",
    rating: 4.8,
    reviews: 158,
    openingHours: "Seg a Sex · 09:00 - 18:00",
    tags: ["Agência", "Parceria", "Alto ticket"],
    aiScore: 89,
    aiSummary: "Agência com carteira B2B; potencial de revenda da plataforma.",
    favorite: false,
    stage: "cliente-fechado",
    createdAt: "2026-07-19T13:20:00Z",
    photos: officePhotos,
  },
];

export const searchHistory: SearchHistoryItem[] = [
  {
    id: "h1",
    query: "Escritórios de Advocacia em Limeira",
    city: "Limeira",
    category: "Advocacia",
    results: 42,
    createdAt: "2026-07-28T09:12:00Z",
  },
  {
    id: "h2",
    query: "Software houses em Campinas",
    city: "Campinas",
    category: "Tecnologia",
    results: 28,
    createdAt: "2026-07-27T17:44:00Z",
  },
  {
    id: "h3",
    query: "Clínicas odontológicas em Piracicaba",
    city: "Piracicaba",
    category: "Saúde",
    results: 61,
    createdAt: "2026-07-27T10:03:00Z",
  },
  {
    id: "h4",
    query: "Imobiliárias em Americana",
    city: "Americana",
    category: "Imobiliário",
    results: 19,
    createdAt: "2026-07-26T15:31:00Z",
  },
  {
    id: "h5",
    query: "Agências de marketing em Limeira",
    city: "Limeira",
    category: "Marketing",
    results: 23,
    createdAt: "2026-07-25T11:08:00Z",
  },
];

export const activities: ActivityItem[] = [
  {
    id: "a1",
    kind: "ai",
    title: "18 empresas analisadas pela IA",
    description: "Score médio 78 · 6 leads classificados como alta prioridade",
    createdAt: "há 12 minutos",
  },
  {
    id: "a2",
    kind: "search",
    title: "Nova pesquisa executada",
    description: "Escritórios de Advocacia em Limeira · 42 resultados",
    createdAt: "há 38 minutos",
  },
  {
    id: "a3",
    kind: "pipeline",
    title: "NorthPeak Software House avançou",
    description: "Proposta Enviada → Negociação",
    createdAt: "há 2 horas",
  },
  {
    id: "a4",
    kind: "system",
    title: "Sincronização com Google Places",
    description: "1.284 registros atualizados no Neon PostgreSQL",
    createdAt: "há 5 horas",
  },
  {
    id: "a5",
    kind: "pipeline",
    title: "Nexo Marketing marcado como cliente",
    description: "Contrato anual · onboarding agendado",
    createdAt: "ontem",
  },
];

export const weeklySeries = [
  { day: "Seg", pesquisas: 12, qualificados: 5 },
  { day: "Ter", pesquisas: 19, qualificados: 9 },
  { day: "Qua", pesquisas: 15, qualificados: 7 },
  { day: "Qui", pesquisas: 27, qualificados: 14 },
  { day: "Sex", pesquisas: 32, qualificados: 18 },
  { day: "Sáb", pesquisas: 9, qualificados: 3 },
  { day: "Dom", pesquisas: 6, qualificados: 2 },
];

export const scoreDistribution = [
  { faixa: "0-40", leads: 12 },
  { faixa: "41-60", leads: 28 },
  { faixa: "61-80", leads: 46 },
  { faixa: "81-100", leads: 31 },
];

export const searchSuggestions = [
  "Escritórios de Advocacia em Limeira",
  "Software houses em Campinas",
  "Clínicas odontológicas em Piracicaba",
  "Contabilidades em Americana",
  "Agências de marketing em Ribeirão Preto",
  "Transportadoras em Sumaré",
];

export const stageLabels: Record<string, string> = {
  "novo-lead": "Novo Lead",
  "primeiro-contato": "Primeiro Contato",
  "reuniao-agendada": "Reunião Agendada",
  "proposta-enviada": "Proposta Enviada",
  negociacao: "Negociação",
  "cliente-fechado": "Cliente Fechado",
  perdido: "Perdido",
};

export const stageOrder = [
  "novo-lead",
  "primeiro-contato",
  "reuniao-agendada",
  "proposta-enviada",
  "negociacao",
  "cliente-fechado",
  "perdido",
] as const;
