/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteImport } from './routes/authenticated'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedBuscarRouteImport } from './routes/authenticated/buscar'
import { Route as AuthenticatedConfiguracoesRouteImport } from './routes/authenticated/configuracoes'
import { Route as AuthenticatedDashboardRouteImport } from './routes/authenticated/dashboard'
import { Route as AuthenticatedHistoricoRouteImport } from './routes/authenticated/historico'
import { Route as AuthenticatedIaRouteImport } from './routes/authenticated/ia'
import { Route as AuthenticatedPerfilRouteImport } from './routes/authenticated/perfil'
import { Route as AuthenticatedPipelineRouteImport } from './routes/authenticated/pipeline'
import { Route as AuthenticatedEmpresasIndexRouteImport } from './routes/authenticated/empresas.index'
import { Route as AuthenticatedEmpresasCompanyIdRouteImport } from './routes/authenticated/empresas.$companyId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/authenticated',
  path: '/authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedBuscarRoute = AuthenticatedBuscarRouteImport.update({
  id: '/buscar',
  path: '/buscar',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedConfiguracoesRoute =
  AuthenticatedConfiguracoesRouteImport.update({
    id: '/configuracoes',
    path: '/configuracoes',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedHistoricoRoute = AuthenticatedHistoricoRouteImport.update({
  id: '/historico',
  path: '/historico',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedIaRoute = AuthenticatedIaRouteImport.update({
  id: '/ia',
  path: '/ia',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPerfilRoute = AuthenticatedPerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPipelineRoute = AuthenticatedPipelineRouteImport.update({
  id: '/pipeline',
  path: '/pipeline',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedEmpresasIndexRoute =
  AuthenticatedEmpresasIndexRouteImport.update({
    id: '/empresas/',
    path: '/empresas/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedEmpresasCompanyIdRoute =
  AuthenticatedEmpresasCompanyIdRouteImport.update({
    id: '/empresas/$companyId',
    path: '/empresas/$companyId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/authenticated/buscar': typeof AuthenticatedBuscarRoute
  '/authenticated/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/authenticated/historico': typeof AuthenticatedHistoricoRoute
  '/authenticated/ia': typeof AuthenticatedIaRoute
  '/authenticated/perfil': typeof AuthenticatedPerfilRoute
  '/authenticated/pipeline': typeof AuthenticatedPipelineRoute
  '/authenticated/empresas/$companyId': typeof AuthenticatedEmpresasCompanyIdRoute
  '/authenticated/empresas/': typeof AuthenticatedEmpresasIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/authenticated/buscar': typeof AuthenticatedBuscarRoute
  '/authenticated/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/authenticated/historico': typeof AuthenticatedHistoricoRoute
  '/authenticated/ia': typeof AuthenticatedIaRoute
  '/authenticated/perfil': typeof AuthenticatedPerfilRoute
  '/authenticated/pipeline': typeof AuthenticatedPipelineRoute
  '/authenticated/empresas/$companyId': typeof AuthenticatedEmpresasCompanyIdRoute
  '/authenticated/empresas': typeof AuthenticatedEmpresasIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/authenticated/buscar': typeof AuthenticatedBuscarRoute
  '/authenticated/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/authenticated/historico': typeof AuthenticatedHistoricoRoute
  '/authenticated/ia': typeof AuthenticatedIaRoute
  '/authenticated/perfil': typeof AuthenticatedPerfilRoute
  '/authenticated/pipeline': typeof AuthenticatedPipelineRoute
  '/authenticated/empresas/$companyId': typeof AuthenticatedEmpresasCompanyIdRoute
  '/authenticated/empresas/': typeof AuthenticatedEmpresasIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/authenticated'
    | '/login'
    | '/authenticated/buscar'
    | '/authenticated/configuracoes'
    | '/authenticated/dashboard'
    | '/authenticated/historico'
    | '/authenticated/ia'
    | '/authenticated/perfil'
    | '/authenticated/pipeline'
    | '/authenticated/empresas/$companyId'
    | '/authenticated/empresas/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/authenticated'
    | '/login'
    | '/authenticated/buscar'
    | '/authenticated/configuracoes'
    | '/authenticated/dashboard'
    | '/authenticated/historico'
    | '/authenticated/ia'
    | '/authenticated/perfil'
    | '/authenticated/pipeline'
    | '/authenticated/empresas/$companyId'
    | '/authenticated/empresas'
  id:
    | '__root__'
    | '/'
    | '/authenticated'
    | '/login'
    | '/authenticated/buscar'
    | '/authenticated/configuracoes'
    | '/authenticated/dashboard'
    | '/authenticated/historico'
    | '/authenticated/ia'
    | '/authenticated/perfil'
    | '/authenticated/pipeline'
    | '/authenticated/empresas/$companyId'
    | '/authenticated/empresas/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/authenticated': {
      id: '/authenticated'
      path: '/authenticated'
      fullPath: '/authenticated'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/authenticated/buscar': {
      id: '/authenticated/buscar'
      path: '/buscar'
      fullPath: '/authenticated/buscar'
      preLoaderRoute: typeof AuthenticatedBuscarRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/authenticated/configuracoes': {
      id: '/authenticated/configuracoes'
      path: '/configuracoes'
      fullPath: '/authenticated/configuracoes'
      preLoaderRoute: typeof AuthenticatedConfiguracoesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/authenticated/dashboard': {
      id: '/authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/authenticated/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/authenticated/historico': {
      id: '/authenticated/historico'
      path: '/historico'
      fullPath: '/authenticated/historico'
      preLoaderRoute: typeof AuthenticatedHistoricoRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/authenticated/ia': {
      id: '/authenticated/ia'
      path: '/ia'
      fullPath: '/authenticated/ia'
      preLoaderRoute: typeof AuthenticatedIaRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/authenticated/perfil': {
      id: '/authenticated/perfil'
      path: '/perfil'
      fullPath: '/authenticated/perfil'
      preLoaderRoute: typeof AuthenticatedPerfilRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/authenticated/pipeline': {
      id: '/authenticated/pipeline'
      path: '/pipeline'
      fullPath: '/authenticated/pipeline'
      preLoaderRoute: typeof AuthenticatedPipelineRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/authenticated/empresas/': {
      id: '/authenticated/empresas/'
      path: '/empresas'
      fullPath: '/authenticated/empresas/'
      preLoaderRoute: typeof AuthenticatedEmpresasIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/authenticated/empresas/$companyId': {
      id: '/authenticated/empresas/$companyId'
      path: '/empresas/$companyId'
      fullPath: '/authenticated/empresas/$companyId'
      preLoaderRoute: typeof AuthenticatedEmpresasCompanyIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedBuscarRoute: typeof AuthenticatedBuscarRoute
  AuthenticatedConfiguracoesRoute: typeof AuthenticatedConfiguracoesRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedHistoricoRoute: typeof AuthenticatedHistoricoRoute
  AuthenticatedIaRoute: typeof AuthenticatedIaRoute
  AuthenticatedPerfilRoute: typeof AuthenticatedPerfilRoute
  AuthenticatedPipelineRoute: typeof AuthenticatedPipelineRoute
  AuthenticatedEmpresasCompanyIdRoute: typeof AuthenticatedEmpresasCompanyIdRoute
  AuthenticatedEmpresasIndexRoute: typeof AuthenticatedEmpresasIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedBuscarRoute: AuthenticatedBuscarRoute,
  AuthenticatedConfiguracoesRoute: AuthenticatedConfiguracoesRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedHistoricoRoute: AuthenticatedHistoricoRoute,
  AuthenticatedIaRoute: AuthenticatedIaRoute,
  AuthenticatedPerfilRoute: AuthenticatedPerfilRoute,
  AuthenticatedPipelineRoute: AuthenticatedPipelineRoute,
  AuthenticatedEmpresasCompanyIdRoute: AuthenticatedEmpresasCompanyIdRoute,
  AuthenticatedEmpresasIndexRoute: AuthenticatedEmpresasIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
